### ISSUE TITLE
Question concerning #68

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/xeus#108]
I was wondering why `xpublisher` and `xheartbeat` are kept as pointers in `xserver_zmq`. This change has been added during @jcfr's PR #68. Is this change useful in SlicerJupyter?

Also, we were wondering why you added non-virtual destructors for those classes on this commit: https://github.com/QuantStack/xeus/pull/68/commits/a569af036263d89252febae8138146b808229d8a. Was your plan to create a custom publisher and a custom heartbeat?

**Comment by jcfr** [comment]
> wondering why xpublisher and xheartbeat are kept as pointers 

Since `xpublisher` and `xheartbeat` were not public, handling them as pointer allows us to forward declare them in `xserver_zmq` while making the server part of the public API.

An other approach would be to follow the pImpl pattern.

> why you added non-virtual destructors for those classes

This is either a left over from a previous version of the PR where `xpublisher` and `xheartbeat`  were made public [most likely] ..  (or it was needed to forward declare  [less likely])
