### ISSUE TITLE
Support integration of xeus in event-loop

### ISSUE THREAD

**Issue by jcfr** [QuantStack/xeus#67]
The current implementation of xserver implements the polling using a while loop and a call to `zmq::poll` without any timeout.

Keeping the current server/server_impl layout, here are possible approaches:

### Approach 1: Allow `xserver_impl` to be derived in application code

To integrate with event-loop based application (e.g a Qt application), a possible approach is to let the application drives the polling with a short timeout (e.g 10ms)

To support this use case, the most straightforward would be to:

* update `xkernel` to support non-blocking implementation of kernel `start()` function: this can be done by keeping track of kernel_id, session_id, server, core and interpreter as ivars

* refactor `xserver_impl::start_impl` introducing `xserver_impl::poll_impl` and `xserver::poll(long timeout)`

* publicly expose `xkernel_core.hpp`, `xpublisher.hpp`, `xheartbeat.hpp` and `xserver_impl.hpp` 
  * they can be moved into the directory `include/xeus/private/`
  * Note: forward declaring `xpublisher` and `xheartbeat` using `std::unique_ptr` in `xserver_impl` is not possible because `xserver_impl` has a virtual destructor and need to be a complete type. Same remark regarding `xkernel_core` and `xkernel`

### Approach 2: Introduce a `xpolling_strategy` object

The `xpolling_strategy` object would be passed to the `xkernel ` constructor.

**Comment by JohanMabille** [comment]
I think the first approach is better, mainly because if we want this part of the code (i.e. `xserver` and its implementation) to be more flexible, at some point we'll need to publicly expose some of the implementations details. Otherwise, future extensions of the current `xserver` base may duplicate a lot of code from `xserver_impl`.

Besides, a polling strategy could even be added later if someones need to customize more than the polling timeout. In that case we'll be happy to have a more flexible API.

I'll continue with my opinion on the technical details in #68

**Comment by jcfr** [comment]
@JohanMabille Thanks for the review and detailed explanation. I addressed all points in PR  #68

**Comment by jcfr** [comment]
Et voila, after #70 is integrated, I should be all set.

**Comment by JohanMabille** [comment]
woot!
